language: python
python:
- 3.5.1
services:
- postgresql
- memcached
env:
- DJANGO=1.9.5
before_install:
- export DJANGO_SETTINGS_MODULE=fredslist.travis-settings
- export PYTHONPATH=$HOME/builds/kjm/fredslist
- export PIP_USER_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE fredslist;" -U postgres
- python manage.py migrate
script:
- coverage run --source='.' manage.py test classifieds userprofiles api
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: Iw5Nhuk80uN+EU+70jP0gr9DXADY/9q5SWEunhgQmPD3p49cH+KGGWcTKbiZUUtff3+lv1niFM5otr3nJUz9/9pMCLACDQPv6je5sbESp5SUxP13fD9vavL11XzynErgDmMHf9rP5/V9qBSxQakjT79vbd/dBy9nkVEc07gLE4wWmOymHsC9fFTg5zrTjIgs+6JacdsAY95nvx+OzJfUzWp4Q+tlyDffhMus3KIOLxGC2GilzSQYI+hdB9cm9C9uNYmJFKToOAy8uaIPJozcgk3fx1b5Mm1qbNJGAICr/iZ8nOJYRgy/dVa0YQAGnJxZj7ttV2RdPYiCay8z18dd4lOkHQjlseVsx94p2WNAXHWJ9if8is6OB0zLsi9za4XdnsU7nho0EvrhbOcfkVrAJjV+G0zV83XE77pZvXhLSjfWuv3lSgy8y84PNCe7pmp2R9fK73flEXSy/biW6Vd+XT4NggAun8iXSwjUfUo7Wn+CVw872MtZCbbSnAPuHWS835jRd1U+9e1YY+UuSZEuroqO/5UqS0usUNFVqn0/w1fgr8ePYTVjsMkckucwSr5dPJoEHmLvQbbjIAiiTeyV6VRa2/pc7F/Z2XJsEC49Ge1ujaBzZbSqKgUZ26QCBcN5VvdG/St2RprWEUVl7mYZHDYC+cW9FWOZk0lrGpyNNac=
  app: glacial-bastion-62815
  on:
    repo: kjmullen/freds-list-assignment
