# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_profile_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
    ]
