# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('userprofiles', '0006_remove_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token'),
        ),
    ]
