# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20160408_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifieds.City'),
        ),
    ]
