# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20160408_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
    ]
