# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0006_auto_20160408_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='listing_picture/default.png', null=True, upload_to='listing_picture/'),
        ),
    ]
