# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 19:49
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0008_auto_20160411_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+1(555)555-5555 format', max_length=128, null=True, verbose_name='Phone Number'),
        ),
    ]
